### ISSUE TITLE
Connect to Ropsten

### ISSUE THREAD

**Issue by blevels** [MaximilianMeister/kuberneteth#6]
Hi, 

I am wondering how can I connect to Ropsten with Kuberneteth. I set the networkId = 3 in the kuberneteth.yaml file, however, that did not produce the desired effect. I would appreciate any assistance you can provide.

Byron

**Comment by MaximilianMeister** [comment]
@blevels the issue is the genesis block, which is the initial thing to do in a fully private ethereum network. to connect to ropsten or another public network, one would need to prevent the genesis block from happening.

a quick way to do this would probably be to comment out these sections (not tested):
* https://github.com/MaximilianMeister/kuberneteth/blob/master/deployment.yaml.erb#L98-L127
* https://github.com/MaximilianMeister/kuberneteth/blob/master/deployment.yaml.erb#L248
* https://github.com/MaximilianMeister/kuberneteth/blob/master/deployment.yaml.erb#L253-L255
* https://github.com/MaximilianMeister/kuberneteth/blob/master/deployment.yaml.erb#L274-L279
* https://github.com/MaximilianMeister/kuberneteth/blob/master/deployment.yaml.erb#L301-L317
* https://github.com/MaximilianMeister/kuberneteth/blob/master/deployment.yaml.erb#L383-L388

**Comment by MaximilianMeister** [comment]
@blevels fixed
